# 100 animal words as a 'secret word' for the user
secret_words = ['reindeer', 'bighorn', 'salamander', 'armadillo', 'coyote',
                'llama', 'leopard', 'opossum', 'mule', 'iguana', 'octopus',
                'woodchuck', 'horse', 'wolf', 'donkey', 'otter', 'sloth',
                'hippopotamus', 'chicken', 'mustang', 'dingo', 'weasel',
                'porpoise', 'baboon', 'beaver', 'crocodile', 'panther',
                'snake', 'wolverine', 'capybara', 'hedgehog', 'seal',
                'gorilla', 'dugong', 'deer', 'rhinoceros', 'okapi',
                'pronghorn', 'pony', 'lovebird', 'lemur', 'dormouse',
                'sheep', 'skunk', 'warthog', 'raccoon', 'guanaco',
                'springbok', 'boar', 'wombat', 'chamois', 'mongoose',
                'hartebeest', 'whale', 'newt', 'coati', 'cougar', 'kangaroo',
                'hyena', 'elephant', 'zebra', 'bear', 'buffalo', 'puma',
                'stallion', 'camel', 'finch', 'marten', 'colt', 'cheetah',
                'badger', 'mole', 'fawn', 'zebu', 'wildcat', 'gnu', 'lynx',
                'hamster', 'gazelle', 'bison', 'monkey', 'lion', 'shrew',
                'fish', 'chameleon', 'hare', 'ermine', 'walrus', 'civet',
                'rabbit', 'oryx', 'panda', 'ibex', 'chipmunk', 'vicuna',
                'dromedary', 'toad', 'kitten', 'yak', 'parakeet']
